### ISSUE TITLE
Addition to readme

### ISSUE THREAD

**Issue by nikvoid** [Zelmoghazy/st-link-v2-clone#2]
It may be necessary to directly connect 3V3 and GND to testpads. I wasn't able to flash my stlink using only SWDIO and SWCLK, with GND and 3V3 on back.

**Comment by Zelmoghazy** [comment]
hmm I think the GND and 3V3 test pads are internally connected to the pins on the back so it shouldnt make much difference, make sure you are connecting to the correct pins

**Comment by Zelmoghazy** [comment]
> It may be necessary to directly connect 3V3 and GND to testpads

hmm I think the GND and 3V3 test pads are internally connected to the pins on the back so it shouldnt make much difference, make sure you are connecting to the correct pins
